@startuml
用户信息正确请求URL -> UrlFilterSecurityInterceptor: Authentication Request
UrlFilterSecurityInterceptor -> UrlMetadataSourceService : getAttributes(Object object)
UrlMetadataSourceService -> UrlConfigAttribute : UrlConfigAttribute(HttpServletRequest httpServletRequest)
UrlMetadataSourceService -> UrlAccessDecisionManager : decide(Authentication authentication, Object object, Collection<ConfigAttribute> configAttributes)
@enduml